version: "3.9"

services:
  # Kafka Producer
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentence-producer
    depends_on:
      - kafka
    networks:
      - stormnet

  # Storm Topology Submitter
  storm-submit:
    image: storm:2.8.2-jre21
    container_name: storm-submit
    depends_on:
      - nimbus
      - kafka
    volumes:
      - ./target/wordcount-topology.jar:/wordcount-topology.jar
    entrypoint: >
      sh -c "storm jar /wordcount-topology.jar com.example.wordcount.WordCountTopology wordcount-topology && tail -f /dev/null"
    networks:
      - stormnet
